edition = "2021"
fn_single_line = false
format_code_in_doc_comments = true
format_strings = true
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
imports_granularity = "One"
reorder_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = false
use_try_shorthand = true
wrap_comments = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_modules = true
unstable_features = true
use_field_init_shorthand = true
format_macro_bodies = true
format_macro_matchers = true
blank_lines_upper_bound = 1
